export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const DEFAULT_PREFERENCE_REPOSITORY = Symbol('DEFAULT_PREFERENCE_REPOSITORY');
export const USER_PREFERENCE_REPOSITORY = Symbol('USER_PREFERENCE_REPOSITORY');
export const POLICY_REPOSITORY = Symbol('POLICY_REPOSITORY');
export const EVALUATION_REPOSITORY = Symbol('EVALUATION_REPOSITORY');
